STRIPE_SK: sk_test_ldilz6awkRKAKpdJ8KlUnt3h
STRIPE_CLIENT_ID: ca_CefKAEpsiwJZKJMW6mc98sgbjIjV8dPI

# publishable_key: pk_test_WOuxu6ZZPDsPH6NEpxUYKagu00nMNIXrtl
# secret_key:      'sk_test_AULa1uC5wSoUXCfjIexEsTc400FA8BSNpZ