default: &default
  adapter: postgresql
  encoding: unicode
development:
  <<: *default
  database: e-commerce_dev
  username: root
  password: root
 

production:
  <<: *default
  database: e-commerce_production
  username: root
  password: root